name: Super Lint Check
on:
  push: null
  pull_request: null
permission: {}
jobs:
  Build:
    name: Lint
    runs-on: ubuntu-latest
    permission:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Super Linter
  uses: super-linter/super-linter@v7.3.0
  env: 
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    VALIDATE_ALL_CODEBASE: true
    DEFAULT_BRANCH: main
    VALIDATE_JAVASCRIPT_ES: true
    VALIDATE_TYPESCRIPT_ES: true
    VALIDATE_JSX: true
    VALIDATE_TSX: true
    VALIDATE_JSON: true
    VALIDATE_MARKDOWN: true
    VALIDATE_YAML: true